Layout
CollectQT/website pull request #6
Opened 2016-12-21 16:59 UTC by tign3y

2016-12-21 23:43 UTC, coilysiren requested changes

2016-12-21 23:43 UTC, lynnco commented on .gitignore
> -
this was a temporary testing change, so this needs to be removed

2016-12-21 23:43 UTC, lynnco commented on webapp/static/css/main.css
> +.heading {
Related to the change above (about gitignoring main.css), this compiled css file needs to be removed

2016-12-21 23:43 UTC, lynnco commented on webapp/templates/head.html
> +<link href="/static/css/main.css" rel="stylesheet">
the line right below this is (`url_for`...) is the one that loads main.css, so this can be removed

2016-12-21 23:43 UTC, lynnco commented on webapp/templates/sidebar.jade
> +
clip this trailing whitespace

2016-12-22 00:23 UTC, coilysiren approved these changes

2016-12-22 09:28 UTC, coilysiren requested changes
Will review the visual changes when I have time!

2016-12-22 09:30 UTC, lynnco commented
Heroku review app ! https://collectqt-pr-6.herokuapp.com/

2016-12-28 02:08 UTC, lynnco commented
drop shadow should be smaller on the right, and possibly also present a bit on the left?

![image](https://cloud.githubusercontent.com/assets/5768468/21512229/676de5ea-cc5f-11e6-9b87-2866fd2d06cf.png)

2016-12-28 02:09 UTC, lynnco commented
(i'm doing these as individual comments because they're easier to read that way, but in a practical sense they're a individual review)

2016-12-28 02:11 UTC, lynnco commented
the description here could use more padding or stand to be text justified, as it currently looks misaligned 
![image](https://cloud.githubusercontent.com/assets/5768468/21512260/d420f452-cc5f-11e6-9180-e902a0d4887e.png)

2016-12-28 02:13 UTC, lynnco commented
These sub headers are.... flat? They could stand to have a less strong background / add a box shadow

![image](https://cloud.githubusercontent.com/assets/5768468/21512270/f97262a4-cc5f-11e6-8a11-001697fab784.png)

2016-12-28 02:15 UTC, lynnco commented
This white on white doesn't look great. Maybe make the entire sidebar off white just a bit? Or... make the sponsor images slightly opaque (like... 95%) and put a dark background underneath them
 
![image](https://cloud.githubusercontent.com/assets/5768468/21512285/4fa49b42-cc60-11e6-99fb-9e12c6388f83.png)

2016-12-28 02:16 UTC, lynnco commented
increase the line height a bit for the paragraph text, also the increase the margins between paragraphs

![image](https://cloud.githubusercontent.com/assets/5768468/21512296/8e29d0a8-cc60-11e6-91c1-4be1dd4a54d9.png)

2016-12-28 02:40 UTC, lynnco commented
actually... I have a bigger idea. Get rid of the sidebar entirely, and all of the sidebar content into the footer ❗️

2016-12-28 02:41 UTC, lynnco commented
(deleted my other sidebar comments)

2016-12-28 02:46 UTC, lynnco commented
I'd like the background gradient to be fixed, instead of scrolling with the page

2016-12-28 03:23 UTC, lynnco commented
Also I'd like the background gradient to not fade to white. Maybe to Quirell's green? I'm not sure, just not white

2016-12-28 03:24 UTC, lynnco commented
✅ All that's going to really change the feel of the page, so that's all of my review for now!

2017-01-03 16:27 UTC, lynnco commented
wrt the background -- its close! but I feel the colors are a bit too eye catching, and draw you away from the center of the page. I'd try one or both of these:

- pastel shades of those colors
- dropping the opacity

![image](https://cloud.githubusercontent.com/assets/5768468/21614314/d4e1abc4-d18d-11e6-9942-4e8617f66a88.png)

2017-01-08 23:18 UTC, lynnco commented
👍 background

2017-01-08 23:19 UTC, lynnco commented
Not sure if its still TODO or you missed it, but old sidebar content should go into the footer (above the `back to top`)

2017-01-11 19:26 UTC, lynnco commented
👍🏼

2017-01-11 22:18 UTC, lynnco commented
It's 95% there! Just a few CSS bugs -

- all the icons but the patreon icon have a highlight on hover, patreon icon needs it too!
- the highlight on hover for the top nav moves the nav downwards when you hover over it

And a few changes

- the "Sponsors" text could use more contrast. Maybe a background, or text shadow
- the sponsors container could use some bottom padding
- there's a very tiny box shadow on the footer, that should be removed

on the home stretch!!!

2017-01-12 01:25 UTC, lynnco commented
👍 👍 👍

2017-01-12 01:31 UTC, lynnco commented
My last thoughts are on mobile css.

- the footer collapses into a hamburger that controls top menu. It should be collapsing vertically, if anything 
- the "article" content should be ~95% width 
- there's a strange right padding issue, where all the content can slide to the left

2017-01-12 01:33 UTC, lynnco commented
Those changes are fairly straightforward, so after they're done you will be finished ✔️

2017-06-04 23:20 UTC, coilysiren approved these changes

2017-06-04 23:20 UTC, lynnco commented
Heya! I'm soooo sorry I should have followed up with you more consistently about this PR! I'm going to merge it now, and handle the last little cleanup bits later.

2017-06-04 23:20 UTC, merged